module.exports = {
	content: ["./index.html", "./src/**/*.{gleam,mjs}"],
	daisyui: {
		themes: [
			{
				light: {
					"primary": "#900000",
					"primary-content": "#ffeeee",
					"secondary": "#f97316",
					"secondary-content": "#111827",
					"accent": "#facc15",
					"accent-content": "#160c00",
					"neutral": "#3D0F18",
					"neutral-content": "#e8e0e8",
					"base-100": "#130404",
					"base-200": "#16160A",
					"base-300": "#302F20",
					"base-content": "#FFF6EE",
					"info": "#7dd3fc",
					"info-content": "#000814",
					"success": "#34d399",
					"success-content": "#020b02",
					"warning": "#fde68a",
					"warning-content": "#160800",
					"error": "#fb7185",
					"error-content": "#140101",

					"--rounded-box": "1rem",
					"--rounded-btn": "0.5rem",
					"--rounded-badge": "1.9rem",
					"--animation-btn": "0.25s",
					"--animation-input": "0.2s",
					"--btn-focus-scale": "0.95",
					"--border-btn": "1px",
					"--tab-border": "1px",
					"--tab-radius": "0.5rem",
				},
				dark: {
					"primary": "#900000",
					"primary-content": "#ffeeee",
					"secondary": "#f97316",
					"secondary-content": "#111827",
					"accent": "#facc15",
					"accent-content": "#160c00",
					"neutral": "#3D0F18",
					"neutral-content": "#e8e0e8",
					"base-100": "#130404",
					"base-200": "#16160A",
					"base-300": "#302F20",
					"base-content": "#FFF6EE",
					"info": "#7dd3fc",
					"info-content": "#000814",
					"success": "#34d399",
					"success-content": "#020b02",
					"warning": "#fde68a",
					"warning-content": "#160800",
					"error": "#fb7185",
					"error-content": "#140101",

					"--rounded-box": "1rem",
					"--rounded-btn": "0.5rem",
					"--rounded-badge": "1.9rem",
					"--animation-btn": "0.25s",
					"--animation-input": "0.2s",
					"--btn-focus-scale": "0.95",
					"--border-btn": "1px",
					"--tab-border": "1px",
					"--tab-radius": "0.5rem",
				},
			},
		],
		darkTheme: "dark",
		base: true,
		styled: true,
		utils: true,
		prefix: "",
		logs: true,
		themeRoot: ":root",
	},
	theme: {
		extend: {
			fontFamily: {
				sans: [
					'"Source Sans 3"',
					"ui-sans-serif",
					"system-ui",
					"sans-serif",
					'"Apple Color Emoji"',
					'"Segoe UI Emoji"',
					'"Segoe UI Symbol"',
					'"Noto Color Emoji"',
				],
				serif: [
					'"Source Serif 4"',
					"ui-serif",
					"Georgia",
					"Cambria",
					'"Times New Roman"',
					"Times",
					"serif",
				],
				mono: [
					'"Source Code Pro"',
					"ui-monospace",
					"SFMono-Regular",
					"Menlo",
					"Monaco",
					"Consolas",
					'"Liberation Mono"',
					'"Courier New"',
					"monospace",
				],
			},
		},
	},
	plugins: [
		require("@tailwindcss/typography"),
		require("@tailwindcss/aspect-ratio"),
		require("./node_modules/daisyui")
	],
};
